// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenmAB3hELd8KFf6lIBdLaqHkJbwUen1M',
    appId: '1:254740265534:web:36d3d30e7360f183a52f6f',
    messagingSenderId: '254740265534',
    projectId: 'fushionwave',
    authDomain: 'fushionwave.firebaseapp.com',
    storageBucket: 'fushionwave.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp4iN_P9gI6fivChwcia1JJ3hQfdW1zqU',
    appId: '1:254740265534:android:9d73e6f7754bfde8a52f6f',
    messagingSenderId: '254740265534',
    projectId: 'fushionwave',
    storageBucket: 'fushionwave.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv32RLjm99NvqT8CaDL6iwduq4JYDebes',
    appId: '1:254740265534:ios:56489a7b086feb0fa52f6f',
    messagingSenderId: '254740265534',
    projectId: 'fushionwave',
    storageBucket: 'fushionwave.firebasestorage.app',
    iosBundleId: 'com.example.fushionwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv32RLjm99NvqT8CaDL6iwduq4JYDebes',
    appId: '1:254740265534:ios:56489a7b086feb0fa52f6f',
    messagingSenderId: '254740265534',
    projectId: 'fushionwave',
    storageBucket: 'fushionwave.firebasestorage.app',
    iosBundleId: 'com.example.fushionwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCenmAB3hELd8KFf6lIBdLaqHkJbwUen1M',
    appId: '1:254740265534:web:aea323bcbe0cfad6a52f6f',
    messagingSenderId: '254740265534',
    projectId: 'fushionwave',
    authDomain: 'fushionwave.firebaseapp.com',
    storageBucket: 'fushionwave.firebasestorage.app',
  );

}